//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWLNBazarHub.EnlaceDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DireccionesEnvio
    {
        public int DireccionID { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public string Direccion { get; set; }
        public string Ciudad { get; set; }
        public string Pais { get; set; }
        public string CodigoPostal { get; set; }
        public string RegistroEstado { get; set; }
        public Nullable<System.DateTime> FechaDeEdicion { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
