//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WABazarHub.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EUsuario", Namespace="http://schemas.datacontract.org/2004/07/SWLNBazarHub.Entidades")]
    [System.SerializableAttribute()]
    public partial class EUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaDeEdicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoUsuarioIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuarioIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaDeEdicion {
            get {
                return this.FechaDeEdicionField;
            }
            set {
                if ((this.FechaDeEdicionField.Equals(value) != true)) {
                    this.FechaDeEdicionField = value;
                    this.RaisePropertyChanged("FechaDeEdicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoUsuarioID {
            get {
                return this.TipoUsuarioIDField;
            }
            set {
                if ((this.TipoUsuarioIDField.Equals(value) != true)) {
                    this.TipoUsuarioIDField = value;
                    this.RaisePropertyChanged("TipoUsuarioID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuarioID {
            get {
                return this.UsuarioIDField;
            }
            set {
                if ((this.UsuarioIDField.Equals(value) != true)) {
                    this.UsuarioIDField = value;
                    this.RaisePropertyChanged("UsuarioID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ETipoUsuario", Namespace="http://schemas.datacontract.org/2004/07/SWLNBazarHub.Entidades")]
    [System.SerializableAttribute()]
    public partial class ETipoUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaDeEdicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoUsuarioIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaDeEdicion {
            get {
                return this.FechaDeEdicionField;
            }
            set {
                if ((this.FechaDeEdicionField.Equals(value) != true)) {
                    this.FechaDeEdicionField = value;
                    this.RaisePropertyChanged("FechaDeEdicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoUsuarioID {
            get {
                return this.TipoUsuarioIDField;
            }
            set {
                if ((this.TipoUsuarioIDField.Equals(value) != true)) {
                    this.TipoUsuarioIDField = value;
                    this.RaisePropertyChanged("TipoUsuarioID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EProductos", Namespace="http://schemas.datacontract.org/2004/07/SWLNBazarHub.Entidades")]
    [System.SerializableAttribute()]
    public partial class EProductos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoriaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaDeEdicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProveedorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoriaID {
            get {
                return this.CategoriaIDField;
            }
            set {
                if ((this.CategoriaIDField.Equals(value) != true)) {
                    this.CategoriaIDField = value;
                    this.RaisePropertyChanged("CategoriaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaDeEdicion {
            get {
                return this.FechaDeEdicionField;
            }
            set {
                if ((this.FechaDeEdicionField.Equals(value) != true)) {
                    this.FechaDeEdicionField = value;
                    this.RaisePropertyChanged("FechaDeEdicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductoID {
            get {
                return this.ProductoIDField;
            }
            set {
                if ((this.ProductoIDField.Equals(value) != true)) {
                    this.ProductoIDField = value;
                    this.RaisePropertyChanged("ProductoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProveedorID {
            get {
                return this.ProveedorIDField;
            }
            set {
                if ((this.ProveedorIDField.Equals(value) != true)) {
                    this.ProveedorIDField = value;
                    this.RaisePropertyChanged("ProveedorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EPedidos", Namespace="http://schemas.datacontract.org/2004/07/SWLNBazarHub.Entidades")]
    [System.SerializableAttribute()]
    public partial class EPedidos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionEnvioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaDeEdicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PedidoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuarioIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionEnvio {
            get {
                return this.DireccionEnvioField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionEnvioField, value) != true)) {
                    this.DireccionEnvioField = value;
                    this.RaisePropertyChanged("DireccionEnvio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaDeEdicion {
            get {
                return this.FechaDeEdicionField;
            }
            set {
                if ((this.FechaDeEdicionField.Equals(value) != true)) {
                    this.FechaDeEdicionField = value;
                    this.RaisePropertyChanged("FechaDeEdicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaPedido {
            get {
                return this.FechaPedidoField;
            }
            set {
                if ((this.FechaPedidoField.Equals(value) != true)) {
                    this.FechaPedidoField = value;
                    this.RaisePropertyChanged("FechaPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PedidoID {
            get {
                return this.PedidoIDField;
            }
            set {
                if ((this.PedidoIDField.Equals(value) != true)) {
                    this.PedidoIDField = value;
                    this.RaisePropertyChanged("PedidoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuarioID {
            get {
                return this.UsuarioIDField;
            }
            set {
                if ((this.UsuarioIDField.Equals(value) != true)) {
                    this.UsuarioIDField = value;
                    this.RaisePropertyChanged("UsuarioID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EDetallesPedido", Namespace="http://schemas.datacontract.org/2004/07/SWLNBazarHub.Entidades")]
    [System.SerializableAttribute()]
    public partial class EDetallesPedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DescuentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DetalleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaDeEdicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PedidoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioUnitarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductoIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Descuento {
            get {
                return this.DescuentoField;
            }
            set {
                if ((this.DescuentoField.Equals(value) != true)) {
                    this.DescuentoField = value;
                    this.RaisePropertyChanged("Descuento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DetalleID {
            get {
                return this.DetalleIDField;
            }
            set {
                if ((this.DetalleIDField.Equals(value) != true)) {
                    this.DetalleIDField = value;
                    this.RaisePropertyChanged("DetalleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaDeEdicion {
            get {
                return this.FechaDeEdicionField;
            }
            set {
                if ((this.FechaDeEdicionField.Equals(value) != true)) {
                    this.FechaDeEdicionField = value;
                    this.RaisePropertyChanged("FechaDeEdicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PedidoID {
            get {
                return this.PedidoIDField;
            }
            set {
                if ((this.PedidoIDField.Equals(value) != true)) {
                    this.PedidoIDField = value;
                    this.RaisePropertyChanged("PedidoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecioUnitario {
            get {
                return this.PrecioUnitarioField;
            }
            set {
                if ((this.PrecioUnitarioField.Equals(value) != true)) {
                    this.PrecioUnitarioField = value;
                    this.RaisePropertyChanged("PrecioUnitario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductoID {
            get {
                return this.ProductoIDField;
            }
            set {
                if ((this.ProductoIDField.Equals(value) != true)) {
                    this.ProductoIDField = value;
                    this.RaisePropertyChanged("ProductoID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EDireccionesEnvio", Namespace="http://schemas.datacontract.org/2004/07/SWLNBazarHub.Entidades")]
    [System.SerializableAttribute()]
    public partial class EDireccionesEnvio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DireccionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaDeEdicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistroEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuarioIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPostal {
            get {
                return this.CodigoPostalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPostalField, value) != true)) {
                    this.CodigoPostalField = value;
                    this.RaisePropertyChanged("CodigoPostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DireccionID {
            get {
                return this.DireccionIDField;
            }
            set {
                if ((this.DireccionIDField.Equals(value) != true)) {
                    this.DireccionIDField = value;
                    this.RaisePropertyChanged("DireccionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaDeEdicion {
            get {
                return this.FechaDeEdicionField;
            }
            set {
                if ((this.FechaDeEdicionField.Equals(value) != true)) {
                    this.FechaDeEdicionField = value;
                    this.RaisePropertyChanged("FechaDeEdicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegistroEstado {
            get {
                return this.RegistroEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistroEstadoField, value) != true)) {
                    this.RegistroEstadoField = value;
                    this.RaisePropertyChanged("RegistroEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuarioID {
            get {
                return this.UsuarioIDField;
            }
            set {
                if ((this.UsuarioIDField.Equals(value) != true)) {
                    this.UsuarioIDField = value;
                    this.RaisePropertyChanged("UsuarioID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EProveedores", Namespace="http://schemas.datacontract.org/2004/07/SWLNBazarHub.Entidades")]
    [System.SerializableAttribute()]
    public partial class EProveedores : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaDeEdicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProveedorIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contacto {
            get {
                return this.ContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactoField, value) != true)) {
                    this.ContactoField = value;
                    this.RaisePropertyChanged("Contacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaDeEdicion {
            get {
                return this.FechaDeEdicionField;
            }
            set {
                if ((this.FechaDeEdicionField.Equals(value) != true)) {
                    this.FechaDeEdicionField = value;
                    this.RaisePropertyChanged("FechaDeEdicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreEmpresa {
            get {
                return this.NombreEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreEmpresaField, value) != true)) {
                    this.NombreEmpresaField = value;
                    this.RaisePropertyChanged("NombreEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProveedorID {
            get {
                return this.ProveedorIDField;
            }
            set {
                if ((this.ProveedorIDField.Equals(value) != true)) {
                    this.ProveedorIDField = value;
                    this.RaisePropertyChanged("ProveedorID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ECategorias", Namespace="http://schemas.datacontract.org/2004/07/SWLNBazarHub.Entidades")]
    [System.SerializableAttribute()]
    public partial class ECategorias : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoriaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaDeEdicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoriaID {
            get {
                return this.CategoriaIDField;
            }
            set {
                if ((this.CategoriaIDField.Equals(value) != true)) {
                    this.CategoriaIDField = value;
                    this.RaisePropertyChanged("CategoriaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaDeEdicion {
            get {
                return this.FechaDeEdicionField;
            }
            set {
                if ((this.FechaDeEdicionField.Equals(value) != true)) {
                    this.FechaDeEdicionField = value;
                    this.RaisePropertyChanged("FechaDeEdicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarUsuario", ReplyAction="http://tempuri.org/IService1/InsertarUsuarioResponse")]
        void InsertarUsuario(WABazarHub.ServiceReference1.EUsuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarUsuario", ReplyAction="http://tempuri.org/IService1/InsertarUsuarioResponse")]
        System.Threading.Tasks.Task InsertarUsuarioAsync(WABazarHub.ServiceReference1.EUsuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarUsuario", ReplyAction="http://tempuri.org/IService1/ActualizarUsuarioResponse")]
        void ActualizarUsuario(WABazarHub.ServiceReference1.EUsuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarUsuario", ReplyAction="http://tempuri.org/IService1/ActualizarUsuarioResponse")]
        System.Threading.Tasks.Task ActualizarUsuarioAsync(WABazarHub.ServiceReference1.EUsuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarUsuarioEstado", ReplyAction="http://tempuri.org/IService1/ActualizarUsuarioEstadoResponse")]
        void ActualizarUsuarioEstado(int usuarioID, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarUsuarioEstado", ReplyAction="http://tempuri.org/IService1/ActualizarUsuarioEstadoResponse")]
        System.Threading.Tasks.Task ActualizarUsuarioEstadoAsync(int usuarioID, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarUsuarioFechaEdicion", ReplyAction="http://tempuri.org/IService1/ActualizarUsuarioFechaEdicionResponse")]
        void ActualizarUsuarioFechaEdicion(int usuarioID, System.DateTime fechaEdicion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarUsuarioFechaEdicion", ReplyAction="http://tempuri.org/IService1/ActualizarUsuarioFechaEdicionResponse")]
        System.Threading.Tasks.Task ActualizarUsuarioFechaEdicionAsync(int usuarioID, System.DateTime fechaEdicion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerTodosUsuarios", ReplyAction="http://tempuri.org/IService1/ObtenerTodosUsuariosResponse")]
        WABazarHub.ServiceReference1.EUsuario[] ObtenerTodosUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerTodosUsuarios", ReplyAction="http://tempuri.org/IService1/ObtenerTodosUsuariosResponse")]
        System.Threading.Tasks.Task<WABazarHub.ServiceReference1.EUsuario[]> ObtenerTodosUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarTipoUsuario", ReplyAction="http://tempuri.org/IService1/InsertarTipoUsuarioResponse")]
        void InsertarTipoUsuario(WABazarHub.ServiceReference1.ETipoUsuario tipoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarTipoUsuario", ReplyAction="http://tempuri.org/IService1/InsertarTipoUsuarioResponse")]
        System.Threading.Tasks.Task InsertarTipoUsuarioAsync(WABazarHub.ServiceReference1.ETipoUsuario tipoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarTipoUsuario", ReplyAction="http://tempuri.org/IService1/ActualizarTipoUsuarioResponse")]
        void ActualizarTipoUsuario(WABazarHub.ServiceReference1.ETipoUsuario tipoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarTipoUsuario", ReplyAction="http://tempuri.org/IService1/ActualizarTipoUsuarioResponse")]
        System.Threading.Tasks.Task ActualizarTipoUsuarioAsync(WABazarHub.ServiceReference1.ETipoUsuario tipoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarTipoUsuarioEstado", ReplyAction="http://tempuri.org/IService1/ActualizarTipoUsuarioEstadoResponse")]
        void ActualizarTipoUsuarioEstado(int tipoUsuarioID, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarTipoUsuarioEstado", ReplyAction="http://tempuri.org/IService1/ActualizarTipoUsuarioEstadoResponse")]
        System.Threading.Tasks.Task ActualizarTipoUsuarioEstadoAsync(int tipoUsuarioID, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarTipoUsuarioFechaEdicion", ReplyAction="http://tempuri.org/IService1/ActualizarTipoUsuarioFechaEdicionResponse")]
        void ActualizarTipoUsuarioFechaEdicion(int tipoUsuarioID, System.DateTime fechaEdicion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarTipoUsuarioFechaEdicion", ReplyAction="http://tempuri.org/IService1/ActualizarTipoUsuarioFechaEdicionResponse")]
        System.Threading.Tasks.Task ActualizarTipoUsuarioFechaEdicionAsync(int tipoUsuarioID, System.DateTime fechaEdicion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerTodosTiposUsuario", ReplyAction="http://tempuri.org/IService1/ObtenerTodosTiposUsuarioResponse")]
        WABazarHub.ServiceReference1.ETipoUsuario[] ObtenerTodosTiposUsuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerTodosTiposUsuario", ReplyAction="http://tempuri.org/IService1/ObtenerTodosTiposUsuarioResponse")]
        System.Threading.Tasks.Task<WABazarHub.ServiceReference1.ETipoUsuario[]> ObtenerTodosTiposUsuarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarProducto", ReplyAction="http://tempuri.org/IService1/InsertarProductoResponse")]
        void InsertarProducto(WABazarHub.ServiceReference1.EProductos producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarProducto", ReplyAction="http://tempuri.org/IService1/InsertarProductoResponse")]
        System.Threading.Tasks.Task InsertarProductoAsync(WABazarHub.ServiceReference1.EProductos producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarProducto", ReplyAction="http://tempuri.org/IService1/ActualizarProductoResponse")]
        void ActualizarProducto(WABazarHub.ServiceReference1.EProductos producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarProducto", ReplyAction="http://tempuri.org/IService1/ActualizarProductoResponse")]
        System.Threading.Tasks.Task ActualizarProductoAsync(WABazarHub.ServiceReference1.EProductos producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarProductoEstado", ReplyAction="http://tempuri.org/IService1/ActualizarProductoEstadoResponse")]
        void ActualizarProductoEstado(int productoID, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarProductoEstado", ReplyAction="http://tempuri.org/IService1/ActualizarProductoEstadoResponse")]
        System.Threading.Tasks.Task ActualizarProductoEstadoAsync(int productoID, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarProductoFechaEdicion", ReplyAction="http://tempuri.org/IService1/ActualizarProductoFechaEdicionResponse")]
        void ActualizarProductoFechaEdicion(int productoID, System.DateTime fechaEdicion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarProductoFechaEdicion", ReplyAction="http://tempuri.org/IService1/ActualizarProductoFechaEdicionResponse")]
        System.Threading.Tasks.Task ActualizarProductoFechaEdicionAsync(int productoID, System.DateTime fechaEdicion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerTodosProductos", ReplyAction="http://tempuri.org/IService1/ObtenerTodosProductosResponse")]
        WABazarHub.ServiceReference1.EProductos[] ObtenerTodosProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerTodosProductos", ReplyAction="http://tempuri.org/IService1/ObtenerTodosProductosResponse")]
        System.Threading.Tasks.Task<WABazarHub.ServiceReference1.EProductos[]> ObtenerTodosProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarPedido", ReplyAction="http://tempuri.org/IService1/InsertarPedidoResponse")]
        void InsertarPedido(WABazarHub.ServiceReference1.EPedidos pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarPedido", ReplyAction="http://tempuri.org/IService1/InsertarPedidoResponse")]
        System.Threading.Tasks.Task InsertarPedidoAsync(WABazarHub.ServiceReference1.EPedidos pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarPedido", ReplyAction="http://tempuri.org/IService1/ActualizarPedidoResponse")]
        void ActualizarPedido(WABazarHub.ServiceReference1.EPedidos pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarPedido", ReplyAction="http://tempuri.org/IService1/ActualizarPedidoResponse")]
        System.Threading.Tasks.Task ActualizarPedidoAsync(WABazarHub.ServiceReference1.EPedidos pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarPedidoEstado", ReplyAction="http://tempuri.org/IService1/ActualizarPedidoEstadoResponse")]
        void ActualizarPedidoEstado(int pedidoID, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarPedidoEstado", ReplyAction="http://tempuri.org/IService1/ActualizarPedidoEstadoResponse")]
        System.Threading.Tasks.Task ActualizarPedidoEstadoAsync(int pedidoID, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarPedidoFechaEdicion", ReplyAction="http://tempuri.org/IService1/ActualizarPedidoFechaEdicionResponse")]
        void ActualizarPedidoFechaEdicion(int pedidoID, System.DateTime fechaEdicion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarPedidoFechaEdicion", ReplyAction="http://tempuri.org/IService1/ActualizarPedidoFechaEdicionResponse")]
        System.Threading.Tasks.Task ActualizarPedidoFechaEdicionAsync(int pedidoID, System.DateTime fechaEdicion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerTodosPedidos", ReplyAction="http://tempuri.org/IService1/ObtenerTodosPedidosResponse")]
        WABazarHub.ServiceReference1.EPedidos[] ObtenerTodosPedidos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerTodosPedidos", ReplyAction="http://tempuri.org/IService1/ObtenerTodosPedidosResponse")]
        System.Threading.Tasks.Task<WABazarHub.ServiceReference1.EPedidos[]> ObtenerTodosPedidosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarDetallePedido", ReplyAction="http://tempuri.org/IService1/InsertarDetallePedidoResponse")]
        void InsertarDetallePedido(WABazarHub.ServiceReference1.EDetallesPedido detallePedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarDetallePedido", ReplyAction="http://tempuri.org/IService1/InsertarDetallePedidoResponse")]
        System.Threading.Tasks.Task InsertarDetallePedidoAsync(WABazarHub.ServiceReference1.EDetallesPedido detallePedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarDetallePedido", ReplyAction="http://tempuri.org/IService1/ActualizarDetallePedidoResponse")]
        void ActualizarDetallePedido(WABazarHub.ServiceReference1.EDetallesPedido detallePedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarDetallePedido", ReplyAction="http://tempuri.org/IService1/ActualizarDetallePedidoResponse")]
        System.Threading.Tasks.Task ActualizarDetallePedidoAsync(WABazarHub.ServiceReference1.EDetallesPedido detallePedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarDetallePedidoEstado", ReplyAction="http://tempuri.org/IService1/ActualizarDetallePedidoEstadoResponse")]
        void ActualizarDetallePedidoEstado(int detalleID, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarDetallePedidoEstado", ReplyAction="http://tempuri.org/IService1/ActualizarDetallePedidoEstadoResponse")]
        System.Threading.Tasks.Task ActualizarDetallePedidoEstadoAsync(int detalleID, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarDetallePedidoFechaEdicion", ReplyAction="http://tempuri.org/IService1/ActualizarDetallePedidoFechaEdicionResponse")]
        void ActualizarDetallePedidoFechaEdicion(int detalleID, System.DateTime fechaEdicion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarDetallePedidoFechaEdicion", ReplyAction="http://tempuri.org/IService1/ActualizarDetallePedidoFechaEdicionResponse")]
        System.Threading.Tasks.Task ActualizarDetallePedidoFechaEdicionAsync(int detalleID, System.DateTime fechaEdicion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerTodosDetallesPedidos", ReplyAction="http://tempuri.org/IService1/ObtenerTodosDetallesPedidosResponse")]
        WABazarHub.ServiceReference1.EDetallesPedido[] ObtenerTodosDetallesPedidos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerTodosDetallesPedidos", ReplyAction="http://tempuri.org/IService1/ObtenerTodosDetallesPedidosResponse")]
        System.Threading.Tasks.Task<WABazarHub.ServiceReference1.EDetallesPedido[]> ObtenerTodosDetallesPedidosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarDireccionEnvio", ReplyAction="http://tempuri.org/IService1/InsertarDireccionEnvioResponse")]
        void InsertarDireccionEnvio(WABazarHub.ServiceReference1.EDireccionesEnvio direccionEnvio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarDireccionEnvio", ReplyAction="http://tempuri.org/IService1/InsertarDireccionEnvioResponse")]
        System.Threading.Tasks.Task InsertarDireccionEnvioAsync(WABazarHub.ServiceReference1.EDireccionesEnvio direccionEnvio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarDireccionEnvio", ReplyAction="http://tempuri.org/IService1/ActualizarDireccionEnvioResponse")]
        void ActualizarDireccionEnvio(WABazarHub.ServiceReference1.EDireccionesEnvio direccionEnvio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarDireccionEnvio", ReplyAction="http://tempuri.org/IService1/ActualizarDireccionEnvioResponse")]
        System.Threading.Tasks.Task ActualizarDireccionEnvioAsync(WABazarHub.ServiceReference1.EDireccionesEnvio direccionEnvio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarDireccionEnvioEstado", ReplyAction="http://tempuri.org/IService1/ActualizarDireccionEnvioEstadoResponse")]
        void ActualizarDireccionEnvioEstado(int direccionID, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarDireccionEnvioEstado", ReplyAction="http://tempuri.org/IService1/ActualizarDireccionEnvioEstadoResponse")]
        System.Threading.Tasks.Task ActualizarDireccionEnvioEstadoAsync(int direccionID, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarDireccionEnvioFechaEdicion", ReplyAction="http://tempuri.org/IService1/ActualizarDireccionEnvioFechaEdicionResponse")]
        void ActualizarDireccionEnvioFechaEdicion(int direccionID, System.DateTime fechaEdicion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarDireccionEnvioFechaEdicion", ReplyAction="http://tempuri.org/IService1/ActualizarDireccionEnvioFechaEdicionResponse")]
        System.Threading.Tasks.Task ActualizarDireccionEnvioFechaEdicionAsync(int direccionID, System.DateTime fechaEdicion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerTodasDireccionesEnvio", ReplyAction="http://tempuri.org/IService1/ObtenerTodasDireccionesEnvioResponse")]
        WABazarHub.ServiceReference1.EDireccionesEnvio[] ObtenerTodasDireccionesEnvio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerTodasDireccionesEnvio", ReplyAction="http://tempuri.org/IService1/ObtenerTodasDireccionesEnvioResponse")]
        System.Threading.Tasks.Task<WABazarHub.ServiceReference1.EDireccionesEnvio[]> ObtenerTodasDireccionesEnvioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarProveedor", ReplyAction="http://tempuri.org/IService1/InsertarProveedorResponse")]
        void InsertarProveedor(WABazarHub.ServiceReference1.EProveedores proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarProveedor", ReplyAction="http://tempuri.org/IService1/InsertarProveedorResponse")]
        System.Threading.Tasks.Task InsertarProveedorAsync(WABazarHub.ServiceReference1.EProveedores proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarProveedor", ReplyAction="http://tempuri.org/IService1/ActualizarProveedorResponse")]
        void ActualizarProveedor(WABazarHub.ServiceReference1.EProveedores proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarProveedor", ReplyAction="http://tempuri.org/IService1/ActualizarProveedorResponse")]
        System.Threading.Tasks.Task ActualizarProveedorAsync(WABazarHub.ServiceReference1.EProveedores proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarProveedorEstado", ReplyAction="http://tempuri.org/IService1/ActualizarProveedorEstadoResponse")]
        void ActualizarProveedorEstado(int proveedorID, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarProveedorEstado", ReplyAction="http://tempuri.org/IService1/ActualizarProveedorEstadoResponse")]
        System.Threading.Tasks.Task ActualizarProveedorEstadoAsync(int proveedorID, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarProveedorFechaEdicion", ReplyAction="http://tempuri.org/IService1/ActualizarProveedorFechaEdicionResponse")]
        void ActualizarProveedorFechaEdicion(int proveedorID, System.DateTime fechaEdicion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarProveedorFechaEdicion", ReplyAction="http://tempuri.org/IService1/ActualizarProveedorFechaEdicionResponse")]
        System.Threading.Tasks.Task ActualizarProveedorFechaEdicionAsync(int proveedorID, System.DateTime fechaEdicion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerTodosProveedores", ReplyAction="http://tempuri.org/IService1/ObtenerTodosProveedoresResponse")]
        WABazarHub.ServiceReference1.EProveedores[] ObtenerTodosProveedores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerTodosProveedores", ReplyAction="http://tempuri.org/IService1/ObtenerTodosProveedoresResponse")]
        System.Threading.Tasks.Task<WABazarHub.ServiceReference1.EProveedores[]> ObtenerTodosProveedoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarCategoria", ReplyAction="http://tempuri.org/IService1/InsertarCategoriaResponse")]
        void InsertarCategoria(WABazarHub.ServiceReference1.ECategorias categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarCategoria", ReplyAction="http://tempuri.org/IService1/InsertarCategoriaResponse")]
        System.Threading.Tasks.Task InsertarCategoriaAsync(WABazarHub.ServiceReference1.ECategorias categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarCategoria", ReplyAction="http://tempuri.org/IService1/ActualizarCategoriaResponse")]
        void ActualizarCategoria(WABazarHub.ServiceReference1.ECategorias categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarCategoria", ReplyAction="http://tempuri.org/IService1/ActualizarCategoriaResponse")]
        System.Threading.Tasks.Task ActualizarCategoriaAsync(WABazarHub.ServiceReference1.ECategorias categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarCategoriaEstado", ReplyAction="http://tempuri.org/IService1/ActualizarCategoriaEstadoResponse")]
        void ActualizarCategoriaEstado(int categoriaID, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarCategoriaEstado", ReplyAction="http://tempuri.org/IService1/ActualizarCategoriaEstadoResponse")]
        System.Threading.Tasks.Task ActualizarCategoriaEstadoAsync(int categoriaID, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarCategoriaFechaEdicion", ReplyAction="http://tempuri.org/IService1/ActualizarCategoriaFechaEdicionResponse")]
        void ActualizarCategoriaFechaEdicion(int categoriaID, System.DateTime fechaEdicion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarCategoriaFechaEdicion", ReplyAction="http://tempuri.org/IService1/ActualizarCategoriaFechaEdicionResponse")]
        System.Threading.Tasks.Task ActualizarCategoriaFechaEdicionAsync(int categoriaID, System.DateTime fechaEdicion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerTodasCategorias", ReplyAction="http://tempuri.org/IService1/ObtenerTodasCategoriasResponse")]
        WABazarHub.ServiceReference1.ECategorias[] ObtenerTodasCategorias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerTodasCategorias", ReplyAction="http://tempuri.org/IService1/ObtenerTodasCategoriasResponse")]
        System.Threading.Tasks.Task<WABazarHub.ServiceReference1.ECategorias[]> ObtenerTodasCategoriasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WABazarHub.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WABazarHub.ServiceReference1.IService1>, WABazarHub.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertarUsuario(WABazarHub.ServiceReference1.EUsuario usuario) {
            base.Channel.InsertarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task InsertarUsuarioAsync(WABazarHub.ServiceReference1.EUsuario usuario) {
            return base.Channel.InsertarUsuarioAsync(usuario);
        }
        
        public void ActualizarUsuario(WABazarHub.ServiceReference1.EUsuario usuario) {
            base.Channel.ActualizarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task ActualizarUsuarioAsync(WABazarHub.ServiceReference1.EUsuario usuario) {
            return base.Channel.ActualizarUsuarioAsync(usuario);
        }
        
        public void ActualizarUsuarioEstado(int usuarioID, string estado) {
            base.Channel.ActualizarUsuarioEstado(usuarioID, estado);
        }
        
        public System.Threading.Tasks.Task ActualizarUsuarioEstadoAsync(int usuarioID, string estado) {
            return base.Channel.ActualizarUsuarioEstadoAsync(usuarioID, estado);
        }
        
        public void ActualizarUsuarioFechaEdicion(int usuarioID, System.DateTime fechaEdicion) {
            base.Channel.ActualizarUsuarioFechaEdicion(usuarioID, fechaEdicion);
        }
        
        public System.Threading.Tasks.Task ActualizarUsuarioFechaEdicionAsync(int usuarioID, System.DateTime fechaEdicion) {
            return base.Channel.ActualizarUsuarioFechaEdicionAsync(usuarioID, fechaEdicion);
        }
        
        public WABazarHub.ServiceReference1.EUsuario[] ObtenerTodosUsuarios() {
            return base.Channel.ObtenerTodosUsuarios();
        }
        
        public System.Threading.Tasks.Task<WABazarHub.ServiceReference1.EUsuario[]> ObtenerTodosUsuariosAsync() {
            return base.Channel.ObtenerTodosUsuariosAsync();
        }
        
        public void InsertarTipoUsuario(WABazarHub.ServiceReference1.ETipoUsuario tipoUsuario) {
            base.Channel.InsertarTipoUsuario(tipoUsuario);
        }
        
        public System.Threading.Tasks.Task InsertarTipoUsuarioAsync(WABazarHub.ServiceReference1.ETipoUsuario tipoUsuario) {
            return base.Channel.InsertarTipoUsuarioAsync(tipoUsuario);
        }
        
        public void ActualizarTipoUsuario(WABazarHub.ServiceReference1.ETipoUsuario tipoUsuario) {
            base.Channel.ActualizarTipoUsuario(tipoUsuario);
        }
        
        public System.Threading.Tasks.Task ActualizarTipoUsuarioAsync(WABazarHub.ServiceReference1.ETipoUsuario tipoUsuario) {
            return base.Channel.ActualizarTipoUsuarioAsync(tipoUsuario);
        }
        
        public void ActualizarTipoUsuarioEstado(int tipoUsuarioID, string estado) {
            base.Channel.ActualizarTipoUsuarioEstado(tipoUsuarioID, estado);
        }
        
        public System.Threading.Tasks.Task ActualizarTipoUsuarioEstadoAsync(int tipoUsuarioID, string estado) {
            return base.Channel.ActualizarTipoUsuarioEstadoAsync(tipoUsuarioID, estado);
        }
        
        public void ActualizarTipoUsuarioFechaEdicion(int tipoUsuarioID, System.DateTime fechaEdicion) {
            base.Channel.ActualizarTipoUsuarioFechaEdicion(tipoUsuarioID, fechaEdicion);
        }
        
        public System.Threading.Tasks.Task ActualizarTipoUsuarioFechaEdicionAsync(int tipoUsuarioID, System.DateTime fechaEdicion) {
            return base.Channel.ActualizarTipoUsuarioFechaEdicionAsync(tipoUsuarioID, fechaEdicion);
        }
        
        public WABazarHub.ServiceReference1.ETipoUsuario[] ObtenerTodosTiposUsuario() {
            return base.Channel.ObtenerTodosTiposUsuario();
        }
        
        public System.Threading.Tasks.Task<WABazarHub.ServiceReference1.ETipoUsuario[]> ObtenerTodosTiposUsuarioAsync() {
            return base.Channel.ObtenerTodosTiposUsuarioAsync();
        }
        
        public void InsertarProducto(WABazarHub.ServiceReference1.EProductos producto) {
            base.Channel.InsertarProducto(producto);
        }
        
        public System.Threading.Tasks.Task InsertarProductoAsync(WABazarHub.ServiceReference1.EProductos producto) {
            return base.Channel.InsertarProductoAsync(producto);
        }
        
        public void ActualizarProducto(WABazarHub.ServiceReference1.EProductos producto) {
            base.Channel.ActualizarProducto(producto);
        }
        
        public System.Threading.Tasks.Task ActualizarProductoAsync(WABazarHub.ServiceReference1.EProductos producto) {
            return base.Channel.ActualizarProductoAsync(producto);
        }
        
        public void ActualizarProductoEstado(int productoID, string estado) {
            base.Channel.ActualizarProductoEstado(productoID, estado);
        }
        
        public System.Threading.Tasks.Task ActualizarProductoEstadoAsync(int productoID, string estado) {
            return base.Channel.ActualizarProductoEstadoAsync(productoID, estado);
        }
        
        public void ActualizarProductoFechaEdicion(int productoID, System.DateTime fechaEdicion) {
            base.Channel.ActualizarProductoFechaEdicion(productoID, fechaEdicion);
        }
        
        public System.Threading.Tasks.Task ActualizarProductoFechaEdicionAsync(int productoID, System.DateTime fechaEdicion) {
            return base.Channel.ActualizarProductoFechaEdicionAsync(productoID, fechaEdicion);
        }
        
        public WABazarHub.ServiceReference1.EProductos[] ObtenerTodosProductos() {
            return base.Channel.ObtenerTodosProductos();
        }
        
        public System.Threading.Tasks.Task<WABazarHub.ServiceReference1.EProductos[]> ObtenerTodosProductosAsync() {
            return base.Channel.ObtenerTodosProductosAsync();
        }
        
        public void InsertarPedido(WABazarHub.ServiceReference1.EPedidos pedido) {
            base.Channel.InsertarPedido(pedido);
        }
        
        public System.Threading.Tasks.Task InsertarPedidoAsync(WABazarHub.ServiceReference1.EPedidos pedido) {
            return base.Channel.InsertarPedidoAsync(pedido);
        }
        
        public void ActualizarPedido(WABazarHub.ServiceReference1.EPedidos pedido) {
            base.Channel.ActualizarPedido(pedido);
        }
        
        public System.Threading.Tasks.Task ActualizarPedidoAsync(WABazarHub.ServiceReference1.EPedidos pedido) {
            return base.Channel.ActualizarPedidoAsync(pedido);
        }
        
        public void ActualizarPedidoEstado(int pedidoID, string estado) {
            base.Channel.ActualizarPedidoEstado(pedidoID, estado);
        }
        
        public System.Threading.Tasks.Task ActualizarPedidoEstadoAsync(int pedidoID, string estado) {
            return base.Channel.ActualizarPedidoEstadoAsync(pedidoID, estado);
        }
        
        public void ActualizarPedidoFechaEdicion(int pedidoID, System.DateTime fechaEdicion) {
            base.Channel.ActualizarPedidoFechaEdicion(pedidoID, fechaEdicion);
        }
        
        public System.Threading.Tasks.Task ActualizarPedidoFechaEdicionAsync(int pedidoID, System.DateTime fechaEdicion) {
            return base.Channel.ActualizarPedidoFechaEdicionAsync(pedidoID, fechaEdicion);
        }
        
        public WABazarHub.ServiceReference1.EPedidos[] ObtenerTodosPedidos() {
            return base.Channel.ObtenerTodosPedidos();
        }
        
        public System.Threading.Tasks.Task<WABazarHub.ServiceReference1.EPedidos[]> ObtenerTodosPedidosAsync() {
            return base.Channel.ObtenerTodosPedidosAsync();
        }
        
        public void InsertarDetallePedido(WABazarHub.ServiceReference1.EDetallesPedido detallePedido) {
            base.Channel.InsertarDetallePedido(detallePedido);
        }
        
        public System.Threading.Tasks.Task InsertarDetallePedidoAsync(WABazarHub.ServiceReference1.EDetallesPedido detallePedido) {
            return base.Channel.InsertarDetallePedidoAsync(detallePedido);
        }
        
        public void ActualizarDetallePedido(WABazarHub.ServiceReference1.EDetallesPedido detallePedido) {
            base.Channel.ActualizarDetallePedido(detallePedido);
        }
        
        public System.Threading.Tasks.Task ActualizarDetallePedidoAsync(WABazarHub.ServiceReference1.EDetallesPedido detallePedido) {
            return base.Channel.ActualizarDetallePedidoAsync(detallePedido);
        }
        
        public void ActualizarDetallePedidoEstado(int detalleID, string estado) {
            base.Channel.ActualizarDetallePedidoEstado(detalleID, estado);
        }
        
        public System.Threading.Tasks.Task ActualizarDetallePedidoEstadoAsync(int detalleID, string estado) {
            return base.Channel.ActualizarDetallePedidoEstadoAsync(detalleID, estado);
        }
        
        public void ActualizarDetallePedidoFechaEdicion(int detalleID, System.DateTime fechaEdicion) {
            base.Channel.ActualizarDetallePedidoFechaEdicion(detalleID, fechaEdicion);
        }
        
        public System.Threading.Tasks.Task ActualizarDetallePedidoFechaEdicionAsync(int detalleID, System.DateTime fechaEdicion) {
            return base.Channel.ActualizarDetallePedidoFechaEdicionAsync(detalleID, fechaEdicion);
        }
        
        public WABazarHub.ServiceReference1.EDetallesPedido[] ObtenerTodosDetallesPedidos() {
            return base.Channel.ObtenerTodosDetallesPedidos();
        }
        
        public System.Threading.Tasks.Task<WABazarHub.ServiceReference1.EDetallesPedido[]> ObtenerTodosDetallesPedidosAsync() {
            return base.Channel.ObtenerTodosDetallesPedidosAsync();
        }
        
        public void InsertarDireccionEnvio(WABazarHub.ServiceReference1.EDireccionesEnvio direccionEnvio) {
            base.Channel.InsertarDireccionEnvio(direccionEnvio);
        }
        
        public System.Threading.Tasks.Task InsertarDireccionEnvioAsync(WABazarHub.ServiceReference1.EDireccionesEnvio direccionEnvio) {
            return base.Channel.InsertarDireccionEnvioAsync(direccionEnvio);
        }
        
        public void ActualizarDireccionEnvio(WABazarHub.ServiceReference1.EDireccionesEnvio direccionEnvio) {
            base.Channel.ActualizarDireccionEnvio(direccionEnvio);
        }
        
        public System.Threading.Tasks.Task ActualizarDireccionEnvioAsync(WABazarHub.ServiceReference1.EDireccionesEnvio direccionEnvio) {
            return base.Channel.ActualizarDireccionEnvioAsync(direccionEnvio);
        }
        
        public void ActualizarDireccionEnvioEstado(int direccionID, string estado) {
            base.Channel.ActualizarDireccionEnvioEstado(direccionID, estado);
        }
        
        public System.Threading.Tasks.Task ActualizarDireccionEnvioEstadoAsync(int direccionID, string estado) {
            return base.Channel.ActualizarDireccionEnvioEstadoAsync(direccionID, estado);
        }
        
        public void ActualizarDireccionEnvioFechaEdicion(int direccionID, System.DateTime fechaEdicion) {
            base.Channel.ActualizarDireccionEnvioFechaEdicion(direccionID, fechaEdicion);
        }
        
        public System.Threading.Tasks.Task ActualizarDireccionEnvioFechaEdicionAsync(int direccionID, System.DateTime fechaEdicion) {
            return base.Channel.ActualizarDireccionEnvioFechaEdicionAsync(direccionID, fechaEdicion);
        }
        
        public WABazarHub.ServiceReference1.EDireccionesEnvio[] ObtenerTodasDireccionesEnvio() {
            return base.Channel.ObtenerTodasDireccionesEnvio();
        }
        
        public System.Threading.Tasks.Task<WABazarHub.ServiceReference1.EDireccionesEnvio[]> ObtenerTodasDireccionesEnvioAsync() {
            return base.Channel.ObtenerTodasDireccionesEnvioAsync();
        }
        
        public void InsertarProveedor(WABazarHub.ServiceReference1.EProveedores proveedor) {
            base.Channel.InsertarProveedor(proveedor);
        }
        
        public System.Threading.Tasks.Task InsertarProveedorAsync(WABazarHub.ServiceReference1.EProveedores proveedor) {
            return base.Channel.InsertarProveedorAsync(proveedor);
        }
        
        public void ActualizarProveedor(WABazarHub.ServiceReference1.EProveedores proveedor) {
            base.Channel.ActualizarProveedor(proveedor);
        }
        
        public System.Threading.Tasks.Task ActualizarProveedorAsync(WABazarHub.ServiceReference1.EProveedores proveedor) {
            return base.Channel.ActualizarProveedorAsync(proveedor);
        }
        
        public void ActualizarProveedorEstado(int proveedorID, string estado) {
            base.Channel.ActualizarProveedorEstado(proveedorID, estado);
        }
        
        public System.Threading.Tasks.Task ActualizarProveedorEstadoAsync(int proveedorID, string estado) {
            return base.Channel.ActualizarProveedorEstadoAsync(proveedorID, estado);
        }
        
        public void ActualizarProveedorFechaEdicion(int proveedorID, System.DateTime fechaEdicion) {
            base.Channel.ActualizarProveedorFechaEdicion(proveedorID, fechaEdicion);
        }
        
        public System.Threading.Tasks.Task ActualizarProveedorFechaEdicionAsync(int proveedorID, System.DateTime fechaEdicion) {
            return base.Channel.ActualizarProveedorFechaEdicionAsync(proveedorID, fechaEdicion);
        }
        
        public WABazarHub.ServiceReference1.EProveedores[] ObtenerTodosProveedores() {
            return base.Channel.ObtenerTodosProveedores();
        }
        
        public System.Threading.Tasks.Task<WABazarHub.ServiceReference1.EProveedores[]> ObtenerTodosProveedoresAsync() {
            return base.Channel.ObtenerTodosProveedoresAsync();
        }
        
        public void InsertarCategoria(WABazarHub.ServiceReference1.ECategorias categoria) {
            base.Channel.InsertarCategoria(categoria);
        }
        
        public System.Threading.Tasks.Task InsertarCategoriaAsync(WABazarHub.ServiceReference1.ECategorias categoria) {
            return base.Channel.InsertarCategoriaAsync(categoria);
        }
        
        public void ActualizarCategoria(WABazarHub.ServiceReference1.ECategorias categoria) {
            base.Channel.ActualizarCategoria(categoria);
        }
        
        public System.Threading.Tasks.Task ActualizarCategoriaAsync(WABazarHub.ServiceReference1.ECategorias categoria) {
            return base.Channel.ActualizarCategoriaAsync(categoria);
        }
        
        public void ActualizarCategoriaEstado(int categoriaID, string estado) {
            base.Channel.ActualizarCategoriaEstado(categoriaID, estado);
        }
        
        public System.Threading.Tasks.Task ActualizarCategoriaEstadoAsync(int categoriaID, string estado) {
            return base.Channel.ActualizarCategoriaEstadoAsync(categoriaID, estado);
        }
        
        public void ActualizarCategoriaFechaEdicion(int categoriaID, System.DateTime fechaEdicion) {
            base.Channel.ActualizarCategoriaFechaEdicion(categoriaID, fechaEdicion);
        }
        
        public System.Threading.Tasks.Task ActualizarCategoriaFechaEdicionAsync(int categoriaID, System.DateTime fechaEdicion) {
            return base.Channel.ActualizarCategoriaFechaEdicionAsync(categoriaID, fechaEdicion);
        }
        
        public WABazarHub.ServiceReference1.ECategorias[] ObtenerTodasCategorias() {
            return base.Channel.ObtenerTodasCategorias();
        }
        
        public System.Threading.Tasks.Task<WABazarHub.ServiceReference1.ECategorias[]> ObtenerTodasCategoriasAsync() {
            return base.Channel.ObtenerTodasCategoriasAsync();
        }
    }
}
